-- Generated by scripts/scrape_clay_art_center_catalog.mjs from clayartcenter.net on 2026-04-10.
delete from public.glaze_firing_images
where glaze_id in (
  select id from public.glazes where brand = 'Clay Art Center' and created_by_user_id is null
);

-- No additional Clay Art Center firing images were bundled in this import.
